version: "3"
services:
  app:
    build:
      context: ./app
    volumes:
     - ./app:.
  db:
    build:
      context: ./db
    image: "mysql:sample"
    ports:
     - "5000:5000"
    environment:
      MYSQL_ROOT_PASWORD: example


