version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file: .env
    depends_on:
      - redis
    volumes:
      - ./webapp:/opt/webapp
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
