version: '3'

services:
  php:
    container_name: php
    build: ./docker/php
    volumes:
     - ./myapp/:/var/www

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      -./myapp:/var/www
      -./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  db:
    image: mysql
    container_name: db
    ports:
      - "5000:5000"
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306


