version: "3.4"
services:
  fronted:
    build:
      context: .
      target: fronted_stage
    image: fronted:latest
  backend:
    build:
      context: .
      target: backend_stage
    image: backend:latest
  final:
    build:
      context: .
      target: final_stage
    image: image:latest
