name: sample2

on:
    schedule:
      - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu
    steps:
      - name: scedule_test
        uses: actions/checkout@v2
        run: echo schedule_test

