name: sample2

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: scedule_test
        env:
          TOKEN: 'hello'
        run: |
          echo 'hi'

