name: sample1

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout dev
        uses: actions/checkout@v2
        with:
          ref: dev


